### ISSUE TITLE
Changed

### ISSUE THREAD

**Issue by Rishikesh-12** [StudentCode-in/Hacktoberfest2020#10]
Do you believe in coping the Readme.md ?

**Comment by Rishikesh-12** [comment]
Just kidding! All the best !

**Comment by Rishikesh-12** [comment]
### _Similar without these marked section._
![image](https://user-images.githubusercontent.com/54947439/95478328-04d21f80-09a7-11eb-9307-d5362cc8cf32.png)

**Comment by akanksha-raghav** [comment]
Will update, sorry for the inconvenience
