### ISSUE TITLE
Regarding PR Greeting test failure. 

### ISSUE THREAD

**Issue by jakaria9001** [StudentCode-in/Hacktoberfest2020#122]
Can someone explain why is almost everyone's PR is failing the greetings test?
What does it actually mean?

**Comment by akanksha-raghav** [comment]
> Can someone explain why is almost everyone's PR is failing the greetings test?
> What does it actually mean?

Hey @jakaria9001 check fail is due to the upstream changes. You can check this to update your fork:
https://dev.to/dhruv194/how-to-update-your-forked-repository-on-github-2m7f
